- name: Create EKS Cluster
  community.aws.eks_cluster:
    name: "{{ cluster_name }}"
    state: "present"
    role_arn: "{{ eks_role.iam_role.arn }}"
    version: "{{ eks_version }}"
    subnets: "{{ subnets.results | map(attribute='subnet.id') | list }}"
    security_groups: 
      - "{{ security_group.group_id }}"
    region: "{{ aws_region }}"
    tags:
      Name: "{{ cluster_name }}"    
  register: eks_cluster
