- name: Create IAM Role for EKS Cluster
  amazon.aws.iam_role:
    name: "{{ cluster_name }}-eks-role"
    state: "present"
    managed_policies:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
    assume_role_policy_document: >
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": { "Service": "eks.amazonaws.com" },
            "Action": "sts:AssumeRole"
          }
        ]
      }
  register: eks_role

- name: Create IAM Policy for EKS Cluster
  amazon.aws.iam_policy:
    policy_name: "{{ cluster_name }}-eks-policy"
    state: "present"
    iam_type: "role"
    iam_name: "{{ eks_role.iam_role.role_name }}"
    policy_json: >
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
          }
        ]
      }
  register: eks_policy
