aws_region: us-east-1
cluster_name: my-eks-cluster
eks_version: 1.31
vpc_cidr: 10.0.0.0/16
public_subnets:
  - cidr: 10.0.1.0/24
    az: us-east-1a
  - cidr: 10.0.2.0/24
    az: us-east-1b
private_subnets:
  - cidr: 10.0.3.0/24
    az: us-east-1a
  - cidr: 10.0.4.0/24
    az: us-east-1b